### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by quicksandznzn** [cookabc/wav2lip_288#1]
https://github.com/cookabc/wav2lip_288/blob/a2ceddb4d4f8da1e135c2bb5fe3988493b8ee4f0/Wav2Lip_288.ipynb#L98C5-L98C5

Would you mind sharing this dataset?

**Comment by cookabc** [comment]
> https://github.com/cookabc/wav2lip_288/blob/a2ceddb4d4f8da1e135c2bb5fe3988493b8ee4f0/Wav2Lip_288.ipynb#L98C5-L98C5
> 
> Would you mind sharing this dataset?

Sorry, the datasets are the property of the company, I cannot share them.
